directory: /radio-stream/music
library: library.db
plugins: metasync duplicates radio_stream fromfilename edit
metasync:
    source: itunes
    itunes:
        library: ~/beets/data/library/iTunes Music Library.xml